# Generated by Django 4.2.13 on 2024-07-12 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
